version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    healthcheck:
        test: [ "CMD", "mysqladmin","ping", "-hlocalhost", "-uroot"]
        start_interval: 1s
        interval: 5s
        timeout: 5s
        retries: 3

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/junmoon/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/junmoon/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
