version: "3"

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:
      - data:/var/www/html
    expose:
      - "443:443"
    networks:
      - "nw"

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - "nw"

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - "nw"

networks:
  nw:
    name: nw
    driver: bridge
